include:
  - local: .gitlab/oscam-helper.yml

variables:
  FF_USE_FASTZIP: 1
  TRANSFER_METER_FREQUENCY: "2s"
  ARTIFACT_COMPRESSION_LEVEL: "default"
  CACHE_COMPRESSION_LEVEL: "default"
  CACHE_REQUEST_TIMEOUT: 5

stages:
  - fixup
  - build
  - deploy
  - new-version
  - sync

info:
  stage: .pre
  tags:
    - build
  variables:
    GIT_STRATEGY: none
  rules:
    - if: $GITLAB_USER_NAME != 'pipeline-user'
  script:
    - !reference [.helper, runner-info]
  allow_failure: true

setup:
  stage: .pre
  tags:
    - build
  variables:
    GIT_STRATEGY: none
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $SETUP_BUILD_ENV == 'True'
    - if: $CI_PIPELINE_SOURCE == 'schedule' && $SETUP_BUILD_ENV == 'True'
  script:
    - !reference [.helper, runner-setup]
  allow_failure: true

oscam-build:
  stage: build
  tags:
    - build
  parallel:
    matrix:
      - ARCH: [native,ancient,latest,aarch64,armv7,mips32el,powerpc,sh4,android12]
        BACKEND: [mbedtls,openssl]
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' || $CI_PIPELINE_SOURCE == 'schedule'
  script:
    - |
      if [[ ! $BUILD_ARCHS =~ $ARCH ]] || [[ ! $BUILD_BACKENDS =~ $BACKEND ]]; then
        echo -e "\e[33mSkipped by configuration: ARCH=${ARCH}, BACKEND=${BACKEND}. Check BUILD_ARCHS/BUILD_BACKENDS.\e[0m";
        exit 0;
      fi
    - !reference [.helper, custom-checkout]
    - !reference [.helper, oscam-build]
  artifacts:
    when: always
    expire_in: 1 hour
    public: false
    paths:
      - build/${ARCH}/oscam-make-${ARCH}-${BACKEND}*
      - build/${ARCH}/oscam-cmake-${ARCH}-${BACKEND}*
  allow_failure: true

.needs_native_matrix:
  matrix:
    - ARCH: [native]
      BACKEND: [mbedtls, openssl]

oscam-test:
  stage: build
  tags:
    - test
  needs:
    - job: oscam-build
      artifacts: true
      parallel: !reference [.needs_native_matrix]
  variables:
    GIT_STRATEGY: none
  parallel:
    matrix:
      - ARCH: [native]
        BACKEND: [mbedtls,openssl]
        OSCAM_BUILD: [make,cmake]
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == 'schedule'
  script:
    - |
      if [[ ! $BUILD_ARCHS =~ $ARCH ]] || [[ ! $BUILD_BACKENDS =~ $BACKEND ]]; then
        echo -e "\e[33mSkipped by configuration: ARCH=${ARCH}, BACKEND=${BACKEND}. Check BUILD_ARCHS/BUILD_BACKENDS.\e[0m";
        exit 0;
      fi
    - !reference [.helper, oscam-startup-test]
  artifacts:
    when: always
    expire_in: 1 hour
    public: false
    paths:
      - build/${ARCH}/oscam-${OSCAM_BUILD}-${ARCH}-${BACKEND}*-test.log
  allow_failure: true

collect-artifacts:
  stage: deploy
  tags:
    - build
  needs:
    - job: oscam-build
      artifacts: true
    - job: oscam-test
      artifacts: true
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == 'schedule'
  script:
    - echo "Collecting build results into deploy/ ..."
    - mkdir -p deploy

    # Collect artifacts keeping directory structure
    - |
      rsync -av build/ deploy/ \
        --include="*/" \
        --include="oscam-*" \
        --include="*.log" \
        --exclude="*"

    # Create bundle archive
    - tar -czf oscam-bundle-${CI_COMMIT_REF_NAME}-${CI_PIPELINE_ID}.tar.gz deploy

    # Generate size report raw data
    - find merged -type f ! -name "*.log" -exec du -k {} \; | sort -k2 | column -t > build-size-report.txt

    - echo "Artifacts collected and size report generated."
  artifacts:
    when: always
    paths:
      - oscam-bundle-${CI_COMMIT_REF_NAME}-${CI_PIPELINE_ID}.tar.gz
      - build-size-report.txt
      - deploy/
    expire_in: 1 week
  allow_failure: true

code-cleanup:
  stage: fixup
  tags:
    - clean
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $GITLAB_USER_NAME != 'pipeline-user'
    - if: $CI_PIPELINE_SOURCE == 'schedule' && $GITLAB_USER_NAME != 'pipeline-user'
  dependencies: []
  script:
    - !reference [.helper, fix-whitespaces]
  allow_failure: true

auto-version:
  stage: new-version
  tags:
    - version
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $GITLAB_USER_NAME != 'pipeline-user'
  script:
    - !reference [.helper, tag-version]
  allow_failure: false

rebase-merge-requests:
  stage: sync
  tags:
    - sync
  needs: [auto-version]
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $GITLAB_USER_NAME != 'pipeline-user'
  script:
    - !reference [.helper, rebase-mrs]
  allow_failure: true

invoke-api-actions:
  stage: sync
  tags:
    - sync
  needs: [auto-version]
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $GITLAB_USER_NAME != 'pipeline-user'
  script:
    - !reference [.helper, invoke-api]
  allow_failure: true
